config/routes.rb
Rails.application.routes.draw do
  resources :protos
  devise_for :users
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to user

  validates :title, presence: true
end

app/models/proto.rb
class Proto < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def create
  end

  private

  def post_params
    params.require(:post).permit(:title).merge(user_id: current_user.id)
  end
end

app/controllers/protos_controller.rb
class ProtosController < ApplicationController
  before_action :set_proto, only: %i[ show edit update destroy ]

  # GET /protos or /protos.json
  def index
    @protos = Proto.all
  end

  # GET /protos/1 or /protos/1.json
  def show
  end

  # GET /protos/new
  def new
    @proto = Proto.new
  end

  # GET /protos/1/edit
  def edit
  end

  # POST /protos or /protos.json
  def create
    @proto = Proto.new(proto_params)

    respond_to do |format|
      if @proto.save
        format.html { redirect_to proto_url(@proto), notice: "Proto was successfully created." }
        format.json { render :show, status: :created, location: @proto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /protos/1 or /protos/1.json
  def update
    respond_to do |format|
      if @proto.update(proto_params)
        format.html { redirect_to proto_url(@proto), notice: "Proto was successfully updated." }
        format.json { render :show, status: :ok, location: @proto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protos/1 or /protos/1.json
  def destroy
    @proto.destroy

    respond_to do |format|
      format.html { redirect_to protos_url, notice: "Proto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proto
      @proto = Proto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proto_params
      params.require(:proto).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/protos_helper.rb
module ProtosHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'ログイン', new_user_session_path %>
  <%= link_to '新規登録', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FavApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/protos/_form.html.erb
<%= form_with(model: proto, local: true) do |form| %>
  <% if proto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proto.errors.count, "error") %> prohibited this proto from being saved:</h2>

      <ul>
        <% proto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/protos/edit.html.erb
<h1>Editing Proto</h1>

<%= render 'form', proto: @proto %>

<%= link_to 'Show', @proto %> |
<%= link_to 'Back', protos_path %>

app/views/protos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Protos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @protos.each do |proto| %>
      <tr>
        <td><%= proto.title %></td>
        <td><%= proto.user_id %></td>
        <td><%= link_to 'Show', proto %></td>
        <td><%= link_to 'Edit', edit_proto_path(proto) %></td>
        <td><%= link_to 'Destroy', proto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proto', new_proto_path %>

app/views/protos/new.html.erb
<h1>New Proto</h1>

<%= render 'form', proto: @proto %>

<%= link_to 'Back', protos_path %>

app/views/protos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @proto.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @proto.user_id %>
</p>

<%= link_to 'Edit', edit_proto_path(@proto) %> |
<%= link_to 'Back', protos_path %>